version: "3"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=scrap
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345 
    
  web:
    build: .
    command: python3 prod_manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db